"""empty message

Revision ID: 1db4dc72ba51
Revises: 8ffc42c311a7
Create Date: 2018-04-15 15:03:09.041025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1db4dc72ba51'
down_revision = '8ffc42c311a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_constraint('items_ibfk_1', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'user', ['userid'], ['id'])
    op.drop_column('items', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ibfk_1', 'items', 'user', ['user'], ['id'])
    op.drop_column('items', 'userid')
    # ### end Alembic commands ###
