"""empty message

Revision ID: 53f8b0d03f20
Revises: a67f4e762dde
Create Date: 2018-01-29 19:19:57.832121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53f8b0d03f20'
down_revision = 'a67f4e762dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastaccess', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('type', sa.String(length=8), nullable=True))
    op.alter_column('user', 'code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['code'])
    op.drop_column('user', 'utype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('utype', mysql.VARCHAR(length=8), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('user', 'type')
    op.drop_column('user', 'lastaccess')
    # ### end Alembic commands ###
