"""empty message

Revision ID: bdd54c814841
Revises: 
Create Date: 2018-01-27 15:54:01.594799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd54c814841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_code', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_firstname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_lastname', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_dob', sa.DATE(), nullable=True),
    sa.Column('user_password', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('user_is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('user_is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('user_datetime_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('sess_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('sess_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sess_created', mysql.DATETIME(), nullable=True),
    sa.Column('sess_last_used', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('sess_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
